"""Generates src/graph_decls.nim: forward declarations for every top-level
proc in the Graph include files, so they can call each other freely."""
import pathlib

src = pathlib.Path(__file__).resolve().parent.parent / 'src'
files = ['graph_model.nim', 'graph_hit.nim', 'graph_overlay.nim', 'graph_input.nim']


def signature(text):
    """The proc header up to the body '=' (outside brackets and strings)."""
    depth = 0
    in_str = False
    i = 0
    while i < len(text):
        c = text[i]
        if in_str:
            if c == '\\':
                i += 2
                continue
            if c == '"':
                in_str = False
        elif c == '"':
            in_str = True
        elif c in '([{':
            depth += 1
        elif c in ')]}':
            depth -= 1
        elif c == '=' and depth == 0:
            prev = text[i - 1] if i else ''
            nxt = text[i + 1] if i + 1 < len(text) else ''
            if prev not in '=<>!' and nxt != '=':
                return text[:i].rstrip()
        i += 1
    return None


out = ['# Generated by tools/gen_decls.py -- forward declarations for graph.nim.', '']
count = 0
for name in files:
    lines = (src / name).read_text().split('\n')
    i = 0
    while i < len(lines):
        if lines[i].startswith('proc '):
            text = lines[i]
            j = i
            sig = signature(text)
            while sig is None:
                j += 1
                text += '\n' + lines[j]
                sig = signature(text)
            out.append(sig)
            count += 1
            i = j + 1
            continue
        i += 1
(src / 'graph_decls.nim').write_text('\n'.join(out) + '\n')
print(count, 'declarations')
