# Generated by tools/gen_decls.py -- forward declarations for graph.nim.

proc emit(g: Graph, name: string, data: Val = nil)
proc getSelection(g: Graph): seq[Val]
proc emitSelection(g: Graph)
proc hasMedia(item: Val): bool
proc mediaItems(items: openArray[Val]): Val
proc rendererSync(g: Graph)
proc rendererUpsert(g: Graph, items: openArray[Val], deferWorker = false)
proc rendererRemove(g: Graph, ids: openArray[string])
proc toast(g: Graph, text: string)
proc defaultLayers(): Val
proc defaultEdgeStyleVal(): Val
proc newGraph*(mobileMode = false): Graph
proc start*(g: Graph)
proc isEmbeddedMedia(s: string): bool
proc snapshot*(g: Graph): string
proc parseSnapshot(g: Graph, data: string): Val
proc commit*(g: Graph, before: string, label = "", hasBefore = true)
proc undo*(g: Graph)
proc redo*(g: Graph)
proc canUndo*(g: Graph): bool
proc canRedo*(g: Graph): bool
proc loadItems*(g: Graph, items: Val, resetHistory = true, layers: Val = nil)
proc diagramVal(g: Graph): Val
proc toJSON*(g: Graph): string
proc fromJSON*(g: Graph, data: Val)
proc maxZ(g: Graph): float64
proc addNode*(g: Graph, data: Val, select = true): Val
proc addEdge*(g: Graph, data: Val, select = true): Val
proc addTemplate*(g: Graph, templ: Val, position: Val = nil, select = true): Val
proc registerEdge(g: Graph, edge: Val)
proc unregisterEdge(g: Graph, edge: Val)
proc reindex(g: Graph, item: Val)
proc rebuildIndex*(g: Graph)
proc reindexNodeAndEdges*(g: Graph, node: Val)
proc getItem*(g: Graph, id: string): Val
proc effectiveGroup(g: Graph, item: Val): string
proc setSelection*(g: Graph, ids: seq[string], exact = false)
proc isSelected*(g: Graph, id: string): bool
proc getCell*(g: Graph, node: Val, row, column: int): Val
proc getSelectedTableCell*(g: Graph): SelectedCell
proc selectTableCell*(g: Graph, node: Val, row, column, rowspan, colspan: int, extend = false): bool
proc selectTableCellBox(g: Graph, node: Val, box: CellBox, extend = false): bool
proc clearTableCellSelection*(g: Graph, notify = true): bool
proc encodeURIComponent(s: string): string
proc decodeURIComponent(s: string): string
proc tableStyleTargetId*(nodeId: string, row, column: int): string
proc parseTableStyleTargetId(id: string): CellTarget
proc tableCellsInRange(g: Graph, node: Val, r0, r1, c0, c1: int): seq[CellBox]
proc tableCellsInSelection(g: Graph, sel: SelectedCell): seq[CellBox]
proc getStyleTargetIds*(g: Graph, allowed: HashSet[string], filtered: bool): seq[string]
proc toggleSelection*(g: Graph, id: string)
proc removeSelection*(g: Graph)
proc copy*(g: Graph)
proc cut*(g: Graph)
proc boundsOfItems*(g: Graph, items: openArray[Val]): (bool, Rect)
proc pasteEdge(g: Graph, source: Val, idMap: Table[string, string], dx, dy: float64): Val
proc paste*(g: Graph, target: Val = nil)
proc duplicate*(g: Graph)
proc changeZ*(g: Graph, front: bool)
proc applyChanges(item, changes: Val)
proc applyTableCellStyle*(g: Graph, node: Val, row, column: int, changes: Val): Val
proc setTableTrackSize(g: Graph, node: Val, axis: string, index: int, value0: Val)
proc normalizeCircularEdge*(g: Graph, edge: Val): Val
proc applyStyle*(g: Graph, changes: Val, label = "", allowed: HashSet[string], filtered: bool)
proc applyStyleAll*(g: Graph, changes: Val, label = "")
proc replaceShape*(g: Graph, targets: seq[Val], templ: Val, label = ""): seq[Val]
proc previewStyle*(g: Graph, ids: seq[string], changes: Val): seq[Val]
proc commitPreview*(g: Graph, before: string, label = "")
proc getCommonStyle*(g: Graph, key: string, fallback: Val): Val
proc selectByType*(g: Graph, kind: string, any: bool)
proc expandToGroups(g: Graph, items: seq[Val]): seq[Val]
proc getGroupMembers*(g: Graph, groupId: string): seq[Val]
proc groupFrame(g: Graph, b: Rect): Rect
proc getSelectedGroups*(g: Graph): seq[GroupInfo]
proc groupFrameAt(g: Graph, p: Pt): (bool, GroupInfo)
proc getGroupHandles(g: Graph, frame: Rect): seq[Handle]
proc enteredDepth(g: Graph, item: Val): int
proc groupSelection*(g: Graph)
proc ungroupSelection*(g: Graph)
proc enterGroup*(g: Graph)
proc exitGroup*(g: Graph)
proc removeFromGroup*(g: Graph)
proc getLayer*(g: Graph, id: string): Val
proc getLayerOf(g: Graph, item: Val): Val
proc addLayer*(g: Graph, name: string): Val
proc removeLayer*(g: Graph, id: string)
proc updateLayer*(g: Graph, id: string, changes: Val)
proc applyLayerOrder(g: Graph)
proc moveLayer*(g: Graph, id: string, delta: int)
proc moveSelectionToLayer*(g: Graph, id: string)
proc isLayerLocked*(g: Graph, item: Val): bool
proc toggleFoldGroup(g: Graph, group: GroupInfo)
proc toggleFold*(g: Graph)
proc toggleContainerFold*(g: Graph, node: Val)
proc tableCellAtWorld*(g: Graph, node: Val, world: Pt): (bool, CellBox)
proc tableRowAt(g: Graph, node: Val, world: Pt): int
proc setCell*(g: Graph, node: Val, row, column: int, value: Val, label = "")
proc resolveTable*(g: Graph, table: Val): Val
proc resizeWeights(weights: Val, count: int): seq[float64]
proc weightsVal(w: seq[float64]): Val
proc createTable*(g: Graph, options0: Val): Val
proc getTableCell*(g: Graph, table: Val, row, column: float64): Val
proc setTableCell*(g: Graph, table: Val, row, column: float64, value, style: Val): bool
proc renumberTableRows(g: Graph, node: Val)
proc remapCells(node: Val, fn: proc (row, column: var float64, cell: Val): bool): Val
proc insertTableRow*(g: Graph, table: Val, index0: Val): bool
proc deleteTableRow*(g: Graph, table: Val, index0: Val): bool
proc insertTableColumn*(g: Graph, table: Val, index0: Val): bool
proc deleteTableColumn*(g: Graph, table: Val, index0: Val): bool
proc mergeTableCells*(g: Graph, table: Val, sr, sc, er, ec: Val): bool
proc splitTableCell*(g: Graph, table: Val, row, column: float64): bool
proc swapTableRows(g: Graph, node: Val, first, second: int, before0: string): bool
proc changeTableSize*(g: Graph, node: Val, rowDelta, columnDelta: float64)
proc insertMedia*(g: Graph, src: string, name: string, point: Val, mediaType: string): Val
proc autosizeSelection*(g: Graph)
proc copySize*(g: Graph)
proc pasteSize*(g: Graph)
proc clearLabels*(g: Graph)
proc deleteAll*(g: Graph)
proc resetView*(g: Graph)
proc fitPage*(g: Graph, widthOnly: bool)
proc toggleLock*(g: Graph)
proc movableNodes(g: Graph): seq[Val]
proc alignSelection*(g: Graph, mode: string)
proc distributeSelection*(g: Graph, axis: string)
proc rotateSelection*(g: Graph, degrees: float64)
proc nudgeSelection*(g: Graph, dx, dy: float64)
proc flipSelection*(g: Graph, axis: string)
proc selectedEdges(g: Graph): seq[Val]
proc resetWaypoints*(g: Graph)
proc addWaypointToSelection*(g: Graph, point: Val)
proc reverseEdges*(g: Graph)
proc flipCircularArc*(g: Graph)
proc copyStyle*(g: Graph)
proc pasteStyle*(g: Graph)
proc setDefaultStyle*(g: Graph)
proc clearDefaultStyle*(g: Graph)
proc getProp*(g: Graph, name: string): Val
proc setProp*(g: Graph, name: string, v: Val)
proc setDiagramOptions*(g: Graph, changes: Val)
proc hiddenLayerIds*(g: Graph): seq[string]
proc getViewState*(g: Graph): Val
proc isGesture(g: Graph): bool
proc render*(g: Graph, forceRealtime = false)
proc getLayoutBounds(g: Graph): (bool, Rect)
proc setSpacer(width, height: float64)
proc updateWorldSize*(g: Graph)
proc setZoom*(g: Graph, value0: float64, hasPoint = false, sx = 0.0, sy = 0.0)
proc zoomIn*(g: Graph)
proc zoomOut*(g: Graph)
proc zoomActual*(g: Graph)
proc getAllBounds*(g: Graph): Rect
proc fit*(g: Graph)
proc eventWorld*(g: Graph, screen: Pt): Pt
proc worldToScreen*(g: Graph, p: Pt): Pt
proc getClickableLinkForCell(g: Graph, item: Val, screen: Pt, forced: bool): string
proc pointInNode*(g: Graph, p: Pt, node: Val): bool
proc compareHit(a, b: Val): int
proc hitTest*(g: Graph, p: Pt, ignoreId = ""): Val
proc nodeOutline(g: Graph, node: Val): seq[Pt]
proc anchorSide(g: Graph, node: Val, nx0, ny0: float64): string
proc normalizedAnchor(g: Graph, node: Val, local: Pt): Val
proc nearestNodeAnchor(g: Graph, node: Val, world: Pt): AnchorInfo
proc getConnectionAnchors(g: Graph, node: Val): seq[Handle]
proc closestCardinalAnchor(g: Graph, node: Val, p: Pt): AnchorInfo
proc classicCardinalAnchor(g: Graph, node: Val, referencePoint: Pt, referenceSide: string,
                           hasReference: bool): AnchorInfo
proc snappedNodeAnchor(g: Graph, node: Val, world: Pt, referencePoint: Pt,
                       referenceSide: string, hasReference: bool): AnchorInfo
proc connectableNode*(g: Graph, node: Val): Val
proc compareConnectionCandidates(a, b: Val): int
proc findConnectionTarget(g: Graph, world: Pt, ignoreId: string, referencePoint: Pt,
                          referenceSide: string, hasReference: bool): AnchorInfo
proc findDirectionalConnectionTarget(g: Graph, source: Val, side: string): DirectionalTarget
proc connectVertex*(g: Graph, source0: Val, side0: string, hasDrop: bool, dropPoint: Pt,
                    before0: string): Val
proc getTableResizeHandles(g: Graph, node: Val): seq[Handle]
proc getTableRowMoveHandles(g: Graph, node: Val): seq[Handle]
proc getNodeHandles(g: Graph, node: Val): seq[Handle]
proc getCustomHandles(g: Graph, node: Val): seq[Handle]
proc getPortArrows(g: Graph, node: Val): seq[Handle]
proc getEdgeHandles(g: Graph, edge: Val): seq[Handle]
proc insertWaypointAt(g: Graph, edge: Val, segmentIndex: int, world: Pt): int
proc snapConnectorPoint(g: Graph, edge: Val, world: Pt, noSnap: bool): Pt
proc waypointAction(g: Graph, world: Pt, noSnap: bool)
proc removeWaypoint*(g: Graph, edge: Val, index: int): bool
proc normalizeEdgeRoute(g: Graph, edge: Val)
proc hitNodeConnectionControl(g: Graph, item: Val, world: Pt): HitControl
proc hitControl*(g: Graph, world: Pt): HitControl
proc drawRoundHandle(g: Graph, ctx: Ctx, p: Pt, fill: string, radius: float64)
proc drawEdgeHandle(g: Graph, ctx: Ctx, p: Pt, fill: string, opacity = 1.0)
proc drawCustomHandle(g: Graph, ctx: Ctx, p: Pt)
proc drawRotationHandle(g: Graph, ctx: Ctx, p: Pt)
proc drawCornerPath(ctx: Ctx, corners: openArray[Pt])
proc drawReplaceTarget(g: Graph, ctx: Ctx, target: ReplaceTarget)
proc drawContainerTarget(g: Graph, ctx: Ctx, node: Val)
proc drawSelectedGroup(g: Graph, ctx: Ctx, group: GroupInfo, controls: bool)
proc drawTableResizeHandles(g: Graph, ctx: Ctx, node: Val)
proc drawTableRowMoveHandles(g: Graph, ctx: Ctx, node: Val)
proc drawPortArrows(g: Graph, ctx: Ctx, node: Val)
proc drawSelectedNode(g: Graph, ctx: Ctx, node: Val, controls: bool)
proc drawSelectedTableCell(g: Graph, ctx: Ctx, sel: SelectedCell)
proc drawConnectionTarget(g: Graph, ctx: Ctx, node: Val, anchor: Val, side: string)
proc drawGuides(g: Graph, ctx: Ctx)
proc drawSelectedEdge(g: Graph, ctx: Ctx, edge: Val)
proc drawConnectionPreview(g: Graph, ctx: Ctx)
proc drawMarquee(g: Graph, ctx: Ctx)
proc drawOverlay*(g: Graph)
proc setCursor(g: Graph, cursor: string)
proc hideTooltip*(g: Graph)
proc updateTooltip(g: Graph, hit: Val)
proc hitFoldingBadge(g: Graph, world: Pt, node: Val): bool
proc toggleFoldFor(g: Graph, node: Val)
proc cloneById(g: Graph, items: openArray[Val], includeLocked = false): OrderedTable[string, Val]
proc getContainedDescendants*(g: Graph, containerIds: seq[string]): seq[Val]
proc selectionCellForHit(g: Graph, hit: Val, alt: bool): Val
proc layoutStackContainer(g: Graph, container: Val): seq[Val]
proc containerDepth(g: Graph, id: string): int
proc layoutStackContainers*(g: Graph, containerIds: seq[string]): seq[Val]
proc extendParentContainersOf*(g: Graph, items: seq[Val]): seq[Val]
proc layoutParentContainersOf(g: Graph, items: seq[Val]): seq[Val]
proc containmentRoots(g: Graph, items: seq[Val]): seq[Val]
proc isDedicatedContainer(g: Graph, item: Val): bool
proc isContainerDropTarget(g: Graph, item: Val, movedIds: HashSet[string]): bool
proc isBlockContainmentItem(g: Graph, item: Val): bool
proc isDescendantOf(g: Graph, item: Val, ancestorId: string): bool
proc itemDepth(g: Graph, item: Val): int
proc findContainerTargets(g: Graph, rootIds: seq[string], movedIds: HashSet[string],
                          hasPointer: bool, pointer: Pt): seq[Val]
proc findContainerTarget(g: Graph, rootIds: seq[string], movedIds: HashSet[string],
                         hasPointer: bool, pointer: Pt): Val
proc finishContainment(g: Graph, action: Action)
proc startMoveAction(g: Graph, world: Pt, before: string): Action
proc startEdgeMoveAction(g: Graph, edge: Val, world: Pt, before: string): Action
proc containerContentBounds(g: Graph, container: Val): Rect
proc stopDragAutoScroll(g: Graph)
proc updateDragAutoScroll(g: Graph, screen: Pt, alt: bool)
proc dragAutoScrollTick*(g: Graph)
proc followMovedConnectorCorners(g: Graph, action: Action, movedIds: HashSet[string],
                                 dx, dy: float64): seq[Val]
proc moveExplicitEdges(g: Graph, action: Action, movedIds: HashSet[string], dx, dy: float64): seq[Val]
proc moveAction(g: Graph, world: Pt, noSnap: bool)
proc edgeMoveAction(g: Graph, world: Pt, noSnap: bool)
proc resizeAction(g: Graph, world: Pt, noSnap: bool)
proc round3(x: float64): float64 {.inline.}
proc customHandleAction(g: Graph, world: Pt, noSnap: bool)
proc tableResizeAction(g: Graph, world: Pt, noSnap: bool)
proc groupResizeAction(g: Graph, world: Pt, noSnap: bool)
proc applyGroupRotation(g: Graph, degrees: float64)
proc groupRotateAction(g: Graph, world: Pt, hardSnap, noSnap: bool)
proc rotateAction(g: Graph, world: Pt, hardSnap, noSnap: bool)
proc circularArcAction(g: Graph, world: Pt, noSnap: bool)
proc segmentAction(g: Graph, world: Pt, noSnap: bool)
proc pointerDown*(g: Graph, ev: PointerEv): int
proc pointerLeave*(g: Graph)
proc pointerMove*(g: Graph, ev: PointerEv): int
proc finishMarquee(g: Graph, action: Action)
proc pointerUp*(g: Graph, ev: PointerEv): int
proc openLink*(g: Graph, href0: string): bool
proc richBlockAt(g: Graph, node: Val, world: Pt): (bool, int, Rect)
proc taskRowAt(g: Graph, node: Val, world: Pt): (bool, int, Rect)
proc startTextEdit*(g: Graph, node: Val, scope: EditScope = EditScope())
proc editAdjacentTask(g: Graph, node: Val, index, direction: int)
proc editAdjacentCell(g: Graph, node: Val, row, column, direction: int)
proc finishTextEdit*(g: Graph, commit: bool)
proc textEditorTab*(g: Graph, backwards: bool)
proc isEditingText*(g: Graph): bool
proc doubleClick*(g: Graph, ev: PointerEv): int
proc startTextEditSelected*(g: Graph)
proc contextMenu*(g: Graph, ev: PointerEv): Val
proc replaceTargetAt(g: Graph, world: Pt): ReplaceTarget
proc dragOver*(g: Graph, screen: Pt, isShapeDrag: bool)
proc clearReplaceTarget*(g: Graph)
proc drop*(g: Graph, screen: Pt, templ: Val): Val
proc keyDown*(g: Graph, key, code: string, shift, ctrl, meta, alt: bool): int
proc keyUp*(g: Graph, code: string)
